[package]
authors = ["Jaroslaw Weber <jaroslaw.weber@gmail.com>"]
name = "vote-for-rust-idea"
version = "0.1.0"

[dependencies]
csv = "0.15.0"
error-chain = "0.11.0"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"
slime = "0.2.0"
toml = "0.4.5"
